language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - npm i -g now

before_script:
  - ls -la

script:
  - npm run build

branches:
  only:
  - master
  - integration

# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   skip_cleanup: true
